### ISSUE TITLE
Πρόβλημα με τις βαθμολογίες ξενοδοχείων

### ISSUE THREAD

**Issue by Rambou** [AegeanHawks/SamosRentals#11]
Κατα την δημιουργία ξενοδοχείου η βαθμολογία είναι by default 2? why?

**Comment by kchasiotis** [comment]
Ας ειναι και -5, δεν ασχολουμε αλλο

**Comment by Rambou** [comment]
:dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :lollipop: :lollipop: :lollipop: :point_right: :ok_hand:

**Comment by Rambou** [comment]
No need for profanity dude....
