### ISSUE TITLE
Pagination empty page

### ISSUE THREAD

**Issue by kchasiotis** [AegeanHawks/SamosRentals#4]
Στη σελίδα hotels το pagination εμφανίζει μια επιπλέον σελίδα η οποία είναι άδεια

**Comment by Rambou** [comment]
Ποίο συγκεκριμένα πότε γίνεται αυτό? Για να αναπαράγω το bug?
Το έτρεξα και δεν υπάρχει τέτοιο θέμα. Είσαι σίγουρος ότι είσαι συγχρονισμένος με την σωστή βάση?

**Comment by Rambou** [comment]
Διωρθώθηκε. Άκυρο issue κύριε @Armageddonas !
